python: can't open file '/tmp/gptme-evals-q064nw5c/hello.py': [Errno 2] No such file or directory
