python: can't open file '/tmp/gptme-evals-3d4upjrd/prime.py': [Errno 2] No such file or directory
