python: can't open file '/tmp/gptme-evals-zkrt42je/prime.py': [Errno 2] No such file or directory
