python: can't open file '/tmp/gptme-evals-q0hlpg84/hello.py': [Errno 2] No such file or directory
