python: can't open file '/tmp/gptme-evals-lox_uwql/hello.py': [Errno 2] No such file or directory
