python: can't open file '/tmp/gptme-evals-jf9u06tm/prime.py': [Errno 2] No such file or directory
