python: can't open file '/tmp/gptme-evals-nd8buhn3/prime.py': [Errno 2] No such file or directory
