python: can't open file '/tmp/gptme-evals-n0w_plqz/prime.py': [Errno 2] No such file or directory
