python: can't open file '/tmp/gptme-evals-b5n7idb2/hello.py': [Errno 2] No such file or directory
