python: can't open file '/tmp/gptme-evals-5us644nj/prime.py': [Errno 2] No such file or directory
