python: can't open file '/tmp/gptme-evals-yuag8cq5/hello.py': [Errno 2] No such file or directory
