python: can't open file '/tmp/gptme-evals-yle7e66n/prime.py': [Errno 2] No such file or directory
