python: can't open file '/tmp/gptme-evals-kc1xn8jb/prime.py': [Errno 2] No such file or directory
