python: can't open file '/tmp/gptme-evals-1n8jc609/prime.py': [Errno 2] No such file or directory
