python: can't open file '/tmp/gptme-evals-a26f9umq/hello.py': [Errno 2] No such file or directory
