python: can't open file '/tmp/gptme-evals-2c6wglnb/hello.py': [Errno 2] No such file or directory
