python: can't open file '/tmp/gptme-evals-zngqeb5w/hello.py': [Errno 2] No such file or directory
