python: can't open file '/tmp/gptme-evals-dpd3xckf/hello.py': [Errno 2] No such file or directory
