python: can't open file '/tmp/gptme-evals-l7i_4uro/prime.py': [Errno 2] No such file or directory
