python: can't open file '/tmp/gptme-evals-j7_l73dp/prime.py': [Errno 2] No such file or directory
