python: can't open file '/tmp/gptme-evals-v2x7pg05/hello.py': [Errno 2] No such file or directory
