python: can't open file '/tmp/gptme-evals-a7td4dbj/prime.py': [Errno 2] No such file or directory
