python: can't open file '/tmp/gptme-evals-k1bznq3h/hello.py': [Errno 2] No such file or directory
