python: can't open file '/tmp/gptme-evals-ect7549h/prime.py': [Errno 2] No such file or directory
