python: can't open file '/tmp/gptme-evals-_x9l_fte/hello.py': [Errno 2] No such file or directory
