python: can't open file '/tmp/gptme-evals-mvheyckx/prime.py': [Errno 2] No such file or directory
