python: can't open file '/tmp/gptme-evals-oejc8ez1/prime.py': [Errno 2] No such file or directory
