python: can't open file '/tmp/gptme-evals-22sqv8xb/hello.py': [Errno 2] No such file or directory
