python: can't open file '/tmp/gptme-evals-km9se8nu/prime.py': [Errno 2] No such file or directory
