python: can't open file '/tmp/gptme-evals-gzx2ar8y/hello.py': [Errno 2] No such file or directory
