python: can't open file '/tmp/gptme-evals-bg6zv4lv/prime.py': [Errno 2] No such file or directory
