python: can't open file '/tmp/gptme-evals-6v6p5eba/hello.py': [Errno 2] No such file or directory
