python: can't open file '/tmp/gptme-evals-oy5817ih/hello.py': [Errno 2] No such file or directory
